sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ltgcy0uCrp1KmTRFA/oEWns9RziddFmr3qfAFo+s/16PhAIrXjxgz6c4V2W1MuVK9gXvZJyu9PmkVIAR9/ElbmHAkka+Ye3Ktxx6S3mxsv8qcs9WApb7CT9Tf5kR7GHC7b5/e30GQjME9E5KW7horCNK3mfdn5rRgoB4DAG6BoeJsCOfSonuejFTD68JezpXBjRvw30eTtvKpYZY6V+cuFdLgZSIxj2UmDmHB0jPlRhEg3Ke1MOHsk8bEwaaqjRM8h3SCW6RRmo6c+1gCsjR1wJdHCySyed3BCC4Eo51Q0bFMIpAyzlrLtQFJ4ZDupZH/kgBS6WyZ+aAmkmQOmw6rlC3XcPc4b+Iibcq32flsakI3lFa+JRI0c/9lqvtimfg7ziQw+nlUGQ4UWI6DqzLxrn8SpQVC8vorXt9P30i6ODVkB453T3EjezwqYSM7cmfHfhC4PLl/4oThBFVI5nScZNikNDaTIMaLwYa7FrWTbM1vJnmLJu/qNK1RU9XITakYehAbTontKiyt3yboKfFanQb75ftFpxH6ILxXUAeBpZLze6OoAd+dT92y33XwwvzNiKp8hI3E6ENI6ZGF7Ft9c2zm9y/qOGujGhLm+zQSqpuEUlMeN+jLPhNFV/8yROSMbmUTt0FRJn/Ri98pmZr3Q6lTyv6YC+QkcdKASsnu0c=
  - secure: S6mb2lI/AtbogSR//POb05ha0O3q5uezY0yt7ywIA8iGbEethA2gq1n6BZ1whg5J6a+AfIshvpYatXAaxj7FhMPKFo4niUdJIhbYYn1dGGwy2xZEKssOJTwbm0+NkgBuS2KGpKj1CTRlDNPy2FLOANB1hF67pCma51/uaJfU4oILnXz+PKtIqU/r64SHWccCdMQycwlZpBIiebsmpn9BYlFQaBdhei4pOiZZ6k/wnZQZUGFmiRnSJXUmmF47xO98DxlbypX1EQmEnh7JOhXV7uTtNY8x1t7Kl5F2y51eFqWOFbYtenjnJ1U4N8ZU0Ufc8JLI4a6UDM+tlOOzlX4nziJihkCtBD/vup9PH5inIBlEZat/viwwku5h2d4ezeHjTwTWlVy8LbtqnNtStjRmAjJk27/3ySG6yr/GSQId6cS1pdw89WFjcai7V4cY5H/jKz3X7ROeX1cHUHEQqfxmIFt+k2b84NEHOzNtjqmUxcJIq9i8qq77PaK2WQkzIin8Q9K1tJ+siTKSlhvDTYsZnWDQ2YZ1fj+V0IYxHkF8bMp96I9gRaPAiNFBtKTHIxLISwbIf2+wFpVrRYVwzwyjkF8hDPJ0M2s7urnONacicYfbh7PZKiFbuQtrWpFVkpsjAP1CKevsSaggwHwC0bO2RKdLAa3wjG5g93RphNelsMs=
  - secure: EcBPfj0NrFR7iVYJzqTxwr0ntXHs1Ids/QTTnJMhNOTAIpyP5DU8nhNTd0bvijmWR541P4UMG4NypxZwV9ljDvpl3XH8AK049YwacI72jgNM6DZlzo1/NGM+Kq5E6sWH31bvEpsjAcTnYgQGEF87xkETKf/TCPjbr4/EoefPE1YOdiFAa63KX8Yh8xZIqKa2swZRWRAQ6DAZn8jRZ6N6J/98REecZ8TTnIX67vCXQKXx+oJKOJgICLXNbSeWaov2UppeAdS79ODCU2GJuJIjYvxOxJQ/lBR01qozeSiYf3qJC2jJb4SpI2J88JMTUIXHJDR6QZWQfXYi2DIhD5rTKt1BEDVvFZ3483OJG+qsGmm/vA8JP98GAYqqKIu2zxH924pohqoaUWjpreIkHRXOuBIQoTT6nvyjUXtbbZo0x+NPXpOHdZVKDLzUQ26AwaGRWjZLkwMikm4Cgm1kSvmhRk/pbPHjcz4jR2vp4mQj28uhi0CRcc6RBbJqP9+O07Fhj4iM8XJohezOR6JcwzYvoIPTBRh4ddA+nlgYp40lJphjl6fUi25qOm5rlbVqnOe170wgI0J+eCKe4hdfZ99Y36XjuMAjMa498cqCg0Y0h4kBjYh/VNhzHZJ2zrDm0pB/Vo53odoGMoOTfqvTieYqauGkACqDoQ6OIbJLzRVubRo=
  - secure: rXI20B/lqKcwF7hHjI2OkD2uRETQRChoTBnq6pJt1p5Mky4PCpaJ3mn3Eoq9Z+YDVDu8XMUilygn/cwmdzHKMk0ZzF2yRzSZEbpf6A33Im1+E0oqcbnVUS6ttDMRs65si/Q+3iSTpCOkvzk01WppC3AfoTeSNVRoggIqKqGLzGNlTbEEepmamfcPjAQaVLGc+GGBp/WLax40+HHINyXcBaXmvG7Wh1KdG5+Rh5USeW8CP4byrHQOReaK/9YRb7zTbmxbHafVsprM6LOmWaEGzKGF4dbyde6pOOrPoU9qvgwuC+W0QpVXMxG5EqkP/pdjcLakW+X44mqi8sdNmUnRNC3cdAWQPFu6NJRLhJ6HI0Jj4sWw6ceua4DloG6XWXUiTnKcDWHxx61RaHrX8+K1/ScI93h4mPD1CpQnjyY5C8UYKqxQmBmcce6unzT9eJTAToZdq+ncv6aWZIjHAwM2k+BQMBQ8lapalfgSlEYCTf3qDjO8iiQzocVdl3nlKwrMkB3Q8RxEKhPedW5xBsjh/vqwBVCw8vpgIXAZCeJ817xTto+jxmNxVboSHxKatXWAYr5BYkBGd7r5fcgBTn0kbZ+6aUOCXjT29r28srfM3OULCRK7rBL3Zm0NQTythmG1so0ZV2jf8+YslQNAMw8vCqBIVKb6Sf+kHYWrXHdkkeE=
